select distinct

	PATIENTID,
	PROVIDERID,
	coalesce(PRIMARYPATIENTINSURANCEID,'unknown') as PRIMARYPATIENTINSURANCEID,
	coalesce(SECONDARYPATIENTINSURANCEID,'unknown') as SECONDARYPATIENTINSURANCEID,
	DEPARTMENTID,
	PATIENTDEPARTMENTID,
	DIAGNOSIS1,
	APPOINTMENTID,
	CAST(CURRENTILLNESSDATE AS DATE) AS CURRENTILLNESSDATE,
	CAST(SERVICEDATE AS DATE) AS SERVICEDATE,
	SUPERVISINGPROVIDERID,
	STATUS1,
	coalesce(STATUS2,'unknown') as status2,
	STATUSP,
	OUTSTANDING1,
	coalesce(OUTSTANDING2,-1) as OUTSTANDING2,
	OUTSTANDINGP,
	CAST(LASTBILLEDDATE1 AS DATE) AS LASTBILLEDDATE1,
	COALESCE(LASTBILLEDDATE2, TO_DATE('1900-01-01')) AS LASTBILLEDDATE2,
	CAST(LASTBILLEDDATEP AS DATE) AS LASTBILLEDDATEP,
	HEALTHCARECLAIMTYPEID1,
	HEALTHCARECLAIMTYPEID2

    from {{ ref('claims') }}