{{ config(
    materialized='table'
) }}

SELECT DISTINCT
    COALESCE(PATIENT_ID, 'unknown') AS PATIENT_ID,
    COALESCE(ORGANIZATION, 'unknown') AS ORGANIZATION,
    COALESCE(PROVIDER, 'unknown') AS PROVIDER,
    COALESCE(PAYER, 'unknown') AS PAYER,
    COALESCE(ENCOUNTERCLASS, 'unknown') AS ENCOUNTERCLASS,
    start_date,
    COALESCE(end_date, '1900-01-01') AS end_date,
    COALESCE(encounter_code, 0000) AS encounter_code,
    COALESCE(DESCRIPTION, 'unknown') AS DESCRIPTION,
    COALESCE(BASE_ENCOUNTER_COST, 0000) AS BASE_ENCOUNTER_COST,
    COALESCE(TOTAL_CLAIM_COST, 0000) AS TOTAL_CLAIM_COST,
    COALESCE(PAYER_COVERAGE, 0000) AS PAYER_COVERAGE,
    COALESCE(CAST(REASONCODE AS VARCHAR(50)), 'NA') AS REASONCODE,
    COALESCE(REASONDESCRIPTION, 'unknown') AS REASONDESCRIPTION
  
FROM {{ ref('encounters') }}