WITH cleaned_patients AS (
  SELECT
    -- 🧩 Identifiers
    TRIM(PATIENT_ID) AS PATIENT_ID,
    REGEXP_REPLACE(FIRST_NAME, '[^A-Za-z]', '') AS FIRST_NAME,
    REGEXP_REPLACE(LAST_NAME, '[^A-Za-z]', '') AS LAST_NAME,

    -- 📅 Dates
BIRTHDATE,
 DEATHDATE,

    -- 🧾 Personal Info
    COALESCE(ACCOUNT_NUMBER, 'unknown') AS ACCOUNT_NUMBER,

    -- ⚧ Demographics
    CASE 
      WHEN GENDER = 'F' THEN 'Female'
      WHEN GENDER = 'M' THEN 'Male'
      WHEN GENDER = 'U' THEN 'Unknown'
      ELSE GENDER
    END AS GENDER,

    REGEXP_REPLACE(RACE, '.*\\^', ' ') AS RACE,
    COALESCE(INITCAP(LOWER(SPLIT_PART(LANGUAGE, '^', 2))), 'unknown') AS LANGUAGE,

    CASE 
      WHEN TRIM(MARITAL_STATUS) IS NULL OR TRIM(MARITAL_STATUS) = '' THEN 'Unknown'
      WHEN POSITION('^' IN MARITAL_STATUS) > 0 THEN INITCAP(TRIM(SPLIT_PART(MARITAL_STATUS, '^', 2)))
      WHEN UPPER(TRIM(MARITAL_STATUS)) = 'M' THEN 'Married'
      WHEN UPPER(TRIM(MARITAL_STATUS)) = 'S' THEN 'Single'
      WHEN UPPER(TRIM(MARITAL_STATUS)) = 'D' THEN 'Divorced'
      WHEN UPPER(TRIM(MARITAL_STATUS)) = 'W' THEN 'Widowed'
      ELSE INITCAP(TRIM(MARITAL_STATUS))
    END AS MARITAL_STATUS,

    COALESCE(INITCAP(LOWER(TRIM(ETHNICITY))), 'unknown') AS ETHNICITY,
    COALESCE(BIRTHPLACE, 'unknown') AS BIRTHPLACE,

    -- 📍 Location
    UPPER(TRIM(ADDRESS)) AS ADDRESS,
    COALESCE(UPPER(TRIM(CITY)), 'unknown') AS CITY,
    COALESCE(UPPER(TRIM(STATE)), 'unknown') AS STATE,
    COALESCE(UPPER(TRIM(COUNTY)), 'unknown') AS COUNTY,

    -- FIPS
    CASE 
      WHEN TRIM(FIPS) IS NULL OR TRIM(FIPS) = '' THEN '25017'
      ELSE CAST(FIPS AS VARCHAR)
    END AS FIPS,

    -- 🌍 Coordinates
    COALESCE(CAST(LAT AS FLOAT), 0.0) AS LATITUDE,
    COALESCE(CAST(LON AS FLOAT), 0.0) AS LONGITUDE,

    -- 💰 Financials
    COALESCE(CAST(HEALTHCARE_EXPENSES AS FLOAT), 0.0) AS HEALTHCARE_EXPENSES,
    COALESCE(CAST(HEALTHCARE_COVERAGE AS FLOAT), -1.0) AS HEALTHCARE_COVERAGE,
    COALESCE(CAST(INCOME AS FLOAT), 0.0) AS INCOME
  FROM {{ ref('patients') }}
)

SELECT DISTINCT * from cleaned_patients